<html>
<HEAD>
<META charset="gb2312"/>
<link href="../css/index.css"  rel="stylesheet" media="screen" type="text/css" />
<TITLE>
</TITLE>
</HEAD>
<BODY>
<div style="width: 100%"><h1 align="center">这里是题库</h1></div>
<div class="frame">
<div >
<iframe src='../index/leftmenu ' class="leftmenu" frameborder="0" id="iframe1" ></iframe>
</div>
<div class=right>
<iframe src='../index/show' class='iframe' frameborder="0" id="iframe" ></iframe>
</div>
</div>

</BODY>
<script type="text/javascript" src="../js/index.js"></script>
</html>