<html>
<head>
<meta charset="gb2312">
<script type="text/javascript"  charset="gbk" src="../ueditor/ueditor.config.js"></script>
<script type="text/javascript"  charset="gbk" src="../ueditor/ueditor.all.min.js"> </script>
</head>
<body>

<div align="center" style="background-color: red;" >
<h1>这里是题目发布系统</h1>
</div>
<div align="center">
<form action="../admin/chkfill" method="post" id="form1" name="form1">
<table>
<tr>
<td>题目类型</td><td>
<a href="../admin/index">选择题</a>
<a href="../admin/fill">填空题</a>
<a href="../admin/readfill">查看题库</a></td> 
</tr>
<!-- 下面就是设计到js的关联选项了  -->
<tr>
<td>所属课本</td><td ><select name="book" id="book">
<option>--选择课本--</option>
</select><input type="button" value="增加课本" onclick="addbook()">
</td>
</tr>
<tr>
<td>所属章节</td><td><select name="chapter" id="chapter">
<option>--选择章节--</option>
</select>
<input type="button" value="增加章节"  onclick="addchapter()"></td>
</tr>
<tr>
<td>题目难度</td><td>困难 <input type="radio" name="class" value="1">
中等 <input type="radio" name="class" value="2">
简单 <input type="radio" name="class" value="3"></td>
</tr>
<tr>
<td>题目分数</td><td><input type="text" name="mark" id="mark"></td>
</tr>
<tr><td>题目内容:</td>
<td style="width: 500px;height: 200px;">
<script type="text/plain" id="textContent"  name="content"> </script>
    <script>
        var editor = new UE.ui.Editor();
        editor.render("textContent");
    </script>
    </td>
</tr>
<tr>
</tr>
<tr>
<td><input type="button" value="添加空位"  onclick="addfill();"></td><td id="fill"></td>
</tr>
<tr>
<td><input type="submit" value="提交" id="sub" ></td><td><input type="reset" value="重写"></td>
</tr>
</table>
</form>
</div>
<script type="text/javascript"  charset="gbk"  src="../js/Ajax.js"></script>
<script type="text/javascript"  charset="gbk"  src="../js/showbook.js"></script>
<script type="text/javascript"  charset="gbk"  src="../js/showchapter.js"></script>
<script type="text/javascript"  charset="gbk"  src="../js/need.js"></script>
<script type="text/javascript">
    n=1;
function addfill(){
	editor.ready(hello());
	input=document.createElement("input");
	input.name="fillname[]";
	input.value="第"+n+"空答案"
	document.getElementById("fill").appendChild(input);
	n++;
}
function hello(){
	editor.setContent(editor.getContentTxt()+"    {%fill%}    "); 
};
    </script>
</body>
</html>