<html>
<head>
<meta charset="gb2312">
</head>
<body>
<div style="width: 800; margin-left: 300px;">
<form action="">

</form>
</div>
<div style="width: 800; margin-left: 300px;">
<ul style="list-style: none; border: 1px solid red;">
<form action="readfill"  method="post">
<table>
<tr>
<td><input type="hidden" name="qtype"  value="2">所属课本：<select name="book" id="book">
<option value="">--选择课本--</option>
</select></td>
<td>所属章节：<select name="chapter" id="chapter">
<option value="">--选择章节--</option></select></td>
<td>题目难度：<select id="class" name="class">
<option value="">不限</option>
<option value="1">困难</option>
<option value="2">中等</option>
<option value="3">简单</option>
</select></td>
<td><input type="submit" value="查询"></td>
</tr>
</table>
</form>  
</ul>
<?php
$i=1;
 foreach ($this->res1 as $value){?>
<ul style="list-style: none; border: 1px solid red;">
<li><?=$i++?>题目:<?=$value['content'] ?><input type="hidden"  name="id[]?>"  value="<?=$value['id'] ?>"></li>
<p align="right" ><a onclick="return confirm('确认删除？');" href="./dele?id=<?=$value['id']; ?>&typeid=<?=$value["typeid"] ?>">删除</a>
|<a href="./updatafill?id=<?=$value['id']?>">修改</a></p></ul>
<?php
 }?>
 <div><?=$this->tip; ?></div>
</div>
</body>
<script type="text/javascript"  charset="gbk"  src="../js/Ajax.js"></script>
<script type="text/javascript"  charset="gbk"  src="../js/showbook.js"></script>
<script type="text/javascript"  charset="gbk"  src="../js/showchapter.js"></script>
</html>