<html>
<head>
<meta charset="gb2312">
</head>
<body>
<div style="width: 800; margin-left: 150px;">
</div>
<div style="width: 800; margin-left: 150px; ">
<ul style="list-style: none; border: 1px solid red;">
<form action="read"  method="post">
<table>
<tr>
<td><input type="hidden" name="qtype"  value="1">所属课本：<select name="book" id="book">
<option value="">--选择课本--</option>
</select></td>
<td>所属章节：<select name="chapter" id="chapter">
<option value="">--选择章节--</option></select></td>
<td>题目难度：<select id="class" name="class">
<option value="">不限</option>
<option value="1">困难</option>
<option value="2">中等</option>
<option value="3">简单</option>
</select></td>
<td><input type="submit" value="查询"></td>
</tr>
</table>
</form>  
</ul>
<?php
$i=1;
 foreach ($this->res1 as $value){?>
<ul style="list-style: none; border: 1px solid red;">
<li><?=$i++?>题目:<?=$value['content'] ?></li>
<li>A:<?=$value['answerA'] ?>&nbsp;&nbsp;
B:<?=$value['answerB'] ?>&nbsp;&nbsp;
C:<?=$value['answerC'] ?>&nbsp;&nbsp;
D:<?=$value['answerD'] ?></li>
<li>正确答案是：<font color='red'><?=$value["answerR"];?></font></li>
<p align="right" ><a onclick="return confirm('确认删除？');" href="./dele?id=<?=$value['id']; ?>&typeid=<?=$value["typeid"];?>">删除</a>
|<a href="./updata?id=<?=$value['id']?>">修改</a></p></ul>
<?php
 }?>
 <div><?=$this->tip; ?></div>
</div>
</body>
<script type="text/javascript"  charset="gbk"  src="../js/Ajax.js"></script>
<script type="text/javascript"  charset="gbk"  src="../js/showbook.js"></script>
<script type="text/javascript"  charset="gbk"  src="../js/showchapter.js"></script>
</html>